version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: igorkolomytsev/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: igorkolomytsev/kittygram_frontend
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: igorkolomytsev/kittygram_gateway
    depends_on:
      - backend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media
