# Generated by Django 3.2.3 on 2024-07-19 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('name',), 'verbose_name': 'достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='achievementcat',
            options={'verbose_name': 'достижение кота', 'verbose_name_plural': 'Достижения кота'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ('name',), 'verbose_name': 'кот', 'verbose_name_plural': 'Коты'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название достижения'),
        ),
        migrations.AlterField(
            model_name='achievementcat',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.achievement', verbose_name='Достижение кота'),
        ),
        migrations.AlterField(
            model_name='achievementcat',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat', verbose_name='Кот'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(through='cats.AchievementCat', to='cats.Achievement', verbose_name='Достижения кота'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='birth_year',
            field=models.IntegerField(verbose_name='Год рождения кота'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(max_length=16, verbose_name='Цвет кота'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='cats/images/', verbose_name='Изображение кота'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Кличка кота'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец кота'),
        ),
    ]
